name: microregistrar
favicon: null
layout_spectrum: 0.86021
typography_spectrum: 0.18429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10483d'
    - '#dbd2cb'
    - '#a4a7a0'
    - '#734106'
    - '#607951'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
